<template>
    <ul class="available-icon-list list-unstyled list">
        <li v-for="icon in availableIcons"
            class=" mb-4">
            <a href="javascript:;" @click="copyToClipboard" v-bind:data-name="icon">
                <div class="icon-icon">
                    <i :class="{ ['icon icon-'+icon]: true }"></i>
                </div>
                <div class="icon-name">
                    {{ icon }}
                </div>
                <div class="icon-success">
                    Copied!
                </div>
            </a>
        </li>
    </ul>
</template>
<style lang="less">
    .available-icon-list {
        display: flex;
        flex-wrap: wrap;

        .icon-icon {
            background-color: rgb(233, 236, 239);
            border-radius: 6px;
            font-size: 32px;
            text-align: center;
            padding: 15px 0;
            color: #333;
        }
        .icon-name, .icon-success {
            color: #4d5b5c;
            text-align: center;
            padding: 10px 0;
            font-size: 12px;
            line-height: 1;
        }
        .icon-success {
            display: none;
        }

        li {
            margin-bottom: 32px;
            margin-right: 18px;
        }

        a {
            display: block;
            text-decoration: none;

            &.copied {
                .icon-name {
                    display: none;
                }
                .icon-success {
                    display: block;
                }
            }
        }

        a:hover {
            .icon-icon, .icon-name {
                color: #7f81ef;
            }
        }
    }
    .available-icon-list li {
        flex: 0 0 auto;
        width: 33.333333%;
    }
    @media (min-width: 576px) {
        .available-icon-list li {
            flex: 0 0 auto;
            width: 25%;
        }
    }
    @media (min-width: 992px) {
        .available-icon-list li {
            flex: 0 0 auto;
            width: 16.666667%;
        }
    }
    @media (min-width: 1200px) {
        .available-icon-list li {
            flex: 0 0 16.666667%;
            width: 16.666667%;
        }
    }
    @media (min-width: 1400px) {
        .available-icon-list li {
            flex: 0 0 12.5%;
            width: 12.5%;
        }
    }

</style>
<script>
    export default {
        name: 'AvailableIcons',
        props: {
        },
        methods: {
            copyToClipboard(ev) {
                const $anchor = ev.target.closest('a');
                let codeToCopy = 'icon-' + $anchor.dataset.name;

                if (navigator.clipboard) {
                    navigator.clipboard.writeText(codeToCopy).then(
                        () => {
                            this.setSuccessTransitions($anchor)
                        },
                        () => {}
                    )
                } else {
                    let copyelement = document.createElement('textarea')
                    document.body.appendChild(copyelement)
                    copyelement.value = codeToCopy
                    copyelement.select()
                    document.execCommand('Copy')
                    copyelement.remove()

                    this.setSuccessTransitions($anchor)
                }
            },
            setSuccessTransitions($anchor) {
                $anchor.classList.add('copied');

                setTimeout(() => {
                    $anchor.classList.remove('copied');
                }, 500);
            }
        },
        data () {
            return {
                availableIcons: [
                    "database-flash",
                    "exit",
                    "app-window",
                    "user-account",
                    "settings",
                    "delete",
                    "fullscreen",
                    "save-cloud",
                    "search-code",
                    "search-up",
                    "angle-down-arrow",
                    "angle-up-arrow",
                    "text-format-ul",
                    "text-format-ol",
                    "fullscreen-collapse",
                    "text-bold",
                    "text-left",
                    "text-right",
                    "text-center",
                    "text-italic",
                    "text-underline",
                    "text-insert-table",
                    "text-justify",
                    "info-circle",
                    "magic-wand",
                    "quote",
                    "horizontal-line",
                    "text-link",
                    "components",
                    "text-strikethrough",
                    "text-colors",
                    "text-emoticons",
                    "text-subscript",
                    "text-superscript",
                    "text-increase-indent",
                    "text-decrease-indent",
                    "text-inline-style",
                    "volume",
                    "text-video",
                    "text-image",
                    "text-redo",
                    "text-undo",
                    "attachment",
                    "edit-code",
                    "cursor-arrow",
                    "text-clear-formatting",
                    "text-eraser",
                    "text-h1",
                    "text-h3",
                    "text-h2",
                    "text-code-block",
                    "preview",
                    "window-split",
                    "list-add",
                    "list-remove",
                    "create",
                    "text-unlink",
                    "check-multi",
                    "add-above",
                    "add-below",
                    "callout-success",
                    "callout-danger",
                    "cross",
                    "callout-info",
                    "text-plus",
                    "log-settings",
                    "power",
                    "text-paint-brush",
                    "mail-branding",
                    "mail-messages",
                    "mail-settings",
                    "mail-templates",
                    "download-cloud",
                    "text-lock",
                    "text-users",
                    "code-snippet",
                    "translate",
                    "globe-site",
                    "id-card-1",
                    "user-group",
                    "user-actions-key",
                    "calendar-add",
                    "calendar-3",
                    "calendar-disable",
                    "calendar-enable",
                    "calendar-clock",
                    "notes-edit",
                    "calendar-check-1",
                    "keyboard-return",
                    "list-reorder",
                    "common-file-remove",
                    "common-file-sync",
                    "harddrive-upload",
                    "common-file-upload",
                    "set-parent",
                    "common-file-star",
                    "add-bold",
                    "layers-grid-add",
                    "collapse",
                    "location-target",
                    "id-badge-1",
                    "language-letters",
                    "address-book",
                    "address-card",
                    "adjust",
                    "align-center",
                    "align-justify",
                    "align-left",
                    "align-right",
                    "ambulance",
                    "american-sign-language-interpreting",
                    "anchor",
                    "android",
                    "angellist",
                    "angle-double-down",
                    "angle-double-left",
                    "angle-double-right",
                    "angle-double-up",
                    "angle-down",
                    "angle-left",
                    "angle-right",
                    "angle-up",
                    "apple",
                    "archive",
                    "area-chart",
                    "arrow-circle-down",
                    "arrow-circle-left",
                    "arrow-circle-right",
                    "arrow-circle-up",
                    "arrow-full-circle-down",
                    "arrow-full-circle-left",
                    "arrow-full-circle-right",
                    "arrow-full-circle-up",
                    "arrow-down",
                    "arrow-left",
                    "arrow-right",
                    "arrow-up",
                    "move",
                    "arrows-alt",
                    "arrows-h",
                    "arrows-v",
                    "asl-interpreting",
                    "assistive-listening-systems",
                    "asterisk",
                    "at",
                    "audio-description",
                    "automobile",
                    "backward",
                    "balance-scale",
                    "ban",
                    "bank",
                    "bar-chart",
                    "barcode",
                    "bars",
                    "bathtub",
                    "battery",
                    "battery-0",
                    "battery-1",
                    "battery-2",
                    "battery-3",
                    "battery-4",
                    "bed",
                    "beer",
                    "bell",
                    "bell-slash",
                    "bicycle",
                    "binoculars",
                    "birthday-cake",
                    "bitcoin",
                    "blind",
                    "bluetooth",
                    "bluetooth-b",
                    "bold",
                    "bolt",
                    "bomb",
                    "book",
                    "bookmark",
                    "braille",
                    "briefcase",
                    "btc",
                    "bug",
                    "building",
                    "bullhorn",
                    "bullseye",
                    "bus",
                    "cab",
                    "calculator",
                    "calendar",
                    "calendar-check",
                    "calendar-minus",
                    "calendar-empty",
                    "calendar-plus",
                    "calendar-times",
                    "camera",
                    "camera-retro",
                    "car",
                    "caret-down",
                    "caret-left",
                    "caret-right",
                    "caret-up",
                    "caret-square-down",
                    "caret-square-left",
                    "caret-square-right",
                    "caret-square-up",
                    "cart-arrow-down",
                    "cart-plus",
                    "cc",
                    "cc-amex",
                    "cc-diners-club",
                    "cc-discover",
                    "cc-jcb",
                    "cc-mastercard",
                    "cc-paypal",
                    "cc-stripe",
                    "cc-visa",
                    "certificate",
                    "chain",
                    "chain-broken",
                    "check",
                    "check-circle",
                    "check-square",
                    "chevron-circle-down",
                    "chevron-circle-left",
                    "chevron-circle-right",
                    "chevron-circle-up",
                    "chevron-down",
                    "chevron-left",
                    "chevron-right",
                    "chevron-up",
                    "child",
                    "chrome",
                    "circle-full",
                    "circle",
                    "circle-notch",
                    "clipboard",
                    "clock",
                    "clone",
                    "close",
                    "cloud",
                    "cloud-download",
                    "cloud-upload",
                    "cny",
                    "code",
                    "code-fork",
                    "coffee",
                    "cog",
                    "cogs",
                    "columns",
                    "comment",
                    "commenting",
                    "comments",
                    "compass",
                    "compress",
                    "copy",
                    "copyright",
                    "creative-commons",
                    "credit-card",
                    "crop",
                    "crosshairs",
                    "css3",
                    "cube",
                    "cubes",
                    "cut",
                    "cutlery",
                    "dashboard",
                    "database",
                    "deaf",
                    "deafness",
                    "dedent",
                    "desktop",
                    "diamond",
                    "dollar",
                    "dot-circle",
                    "download",
                    "dribbble",
                    "drivers-license",
                    "edge",
                    "edit",
                    "eject",
                    "ellipsis-h",
                    "ellipsis-v",
                    "envelope",
                    "envelope-open",
                    "envelope-square",
                    "leaf-2",
                    "eraser",
                    "eur",
                    "euro",
                    "exchange",
                    "exclamation",
                    "exclamation-circle",
                    "exclamation-triangle",
                    "expand",
                    "external-link",
                    "external-link-square-link-square",
                    "eye",
                    "eye-slash",
                    "eyedropper",
                    "fa",
                    "fast-backward",
                    "fast-forward",
                    "fax",
                    "feed",
                    "female",
                    "fighter-jet",
                    "file",
                    "file-archive",
                    "file-audio",
                    "file-code",
                    "file-excel",
                    "file-image",
                    "file-movie",
                    "file-pdf",
                    "file-photo",
                    "file-picture",
                    "file-powerpoint",
                    "file-sound",
                    "file-text",
                    "file-video",
                    "file-word",
                    "file-zip",
                    "files",
                    "film",
                    "filter",
                    "fire",
                    "fire-extinguisher",
                    "flag",
                    "flag-checkered",
                    "flash",
                    "flask",
                    "floppy",
                    "folder",
                    "folder-open",
                    "font",
                    "forward",
                    "frown",
                    "futbol",
                    "gamepad",
                    "legal",
                    "gbp",
                    "gear",
                    "gears",
                    "genderless",
                    "gift",
                    "git",
                    "git-square",
                    "glass",
                    "globe",
                    "google",
                    "graduation-cap",
                    "october",
                    "group",
                    "hand-grab",
                    "hand-lizard",
                    "hand-down",
                    "hand-left",
                    "hand-right",
                    "hand-up",
                    "hand-paper",
                    "hand-peace",
                    "hand-pointer",
                    "hand-rock",
                    "hand-scissors",
                    "hand-spock",
                    "hand-stop",
                    "handshake",
                    "hard-of-hearing",
                    "hashtag",
                    "hdd",
                    "header",
                    "headphones",
                    "heart",
                    "heartbeat",
                    "history",
                    "home",
                    "hospital",
                    "hotel",
                    "hourglass-0",
                    "hourglass-1",
                    "hourglass-2",
                    "hourglass-3",
                    "html5",
                    "i-cursor",
                    "id-badge",
                    "id-card",
                    "ils",
                    "image",
                    "inbox",
                    "indent",
                    "industry",
                    "info",
                    "info-circle-1",
                    "inr",
                    "instagram",
                    "institution",
                    "intersex",
                    "italic",
                    "jpy",
                    "key",
                    "keyboard",
                    "krw",
                    "language",
                    "laptop",
                    "leaf",
                    "legal-1",
                    "lemon",
                    "life-bouy",
                    "life-buoy",
                    "life-ring",
                    "life-saver",
                    "lightbulb",
                    "line-chart",
                    "link",
                    "linux",
                    "list",
                    "list-alt",
                    "list-ol",
                    "list-ul",
                    "location-arrow",
                    "lock",
                    "long-arrow-down",
                    "long-arrow-left",
                    "long-arrow-right",
                    "long-arrow-up",
                    "low-vision",
                    "magic",
                    "magnet",
                    "mail-forward",
                    "mail-reply",
                    "mail-reply-all",
                    "level-up",
                    "level-down",
                    "male",
                    "map-marker",
                    "map",
                    "map-pin",
                    "map-signs",
                    "mars",
                    "mars-double",
                    "mars-stroke",
                    "mars-stroke-h",
                    "mars-stroke-v",
                    "medkit",
                    "meh",
                    "mercury",
                    "microchip",
                    "microphone",
                    "microphone-slash",
                    "minus",
                    "minus-circle",
                    "minus-square",
                    "mobile",
                    "money",
                    "moon",
                    "mortar-board",
                    "motorcycle",
                    "mouse-pointer",
                    "music",
                    "navicon",
                    "neuter",
                    "newspaper",
                    "object-group",
                    "object-ungroup",
                    "outdent",
                    "pagelines",
                    "paint-brush",
                    "paper-plane",
                    "paperclip",
                    "paragraph",
                    "paste",
                    "pause",
                    "pause-circle",
                    "paw",
                    "pencil",
                    "pencil-square",
                    "pencil-square-1",
                    "percent",
                    "phone",
                    "phone-square",
                    "photo",
                    "pie-chart",
                    "plane",
                    "play",
                    "play-circle",
                    "plug",
                    "plus",
                    "plus-circle",
                    "plus-square",
                    "podcast",
                    "power-off",
                    "print",
                    "puzzle-piece",
                    "qrcode",
                    "question",
                    "question-circle",
                    "quote-left",
                    "quote-right",
                    "random",
                    "recycle",
                    "refresh",
                    "registered",
                    "remove",
                    "reorder",
                    "repeat",
                    "retweet",
                    "rmb",
                    "road",
                    "rocket",
                    "rotate-left",
                    "rotate-right",
                    "rouble",
                    "rss",
                    "rss-square-square",
                    "rub",
                    "ruble",
                    "rupee",
                    "s15",
                    "safari",
                    "save",
                    "scissors",
                    "search",
                    "search-minus",
                    "search-plus",
                    "send",
                    "server",
                    "share-alt",
                    "share-alt-square",
                    "share-square",
                    "shekel",
                    "shield",
                    "ship",
                    "shopping-bag",
                    "shopping-basket",
                    "shopping-cart",
                    "shower",
                    "sign-in",
                    "sign-language",
                    "sign-out",
                    "signal",
                    "signing",
                    "sitemap",
                    "sliders",
                    "smile",
                    "snowflake",
                    "soccer-ball",
                    "sort",
                    "sort-alpha-asc",
                    "sort-alpha-desc",
                    "sort-amount-asc",
                    "sort-amount-desc",
                    "sort-down",
                    "sort-numeric-asc",
                    "sort-numeric-desc",
                    "sort-up",
                    "space-shuttle",
                    "spinner",
                    "spoon",
                    "square",
                    "star-full",
                    "star-half",
                    "star-half-full",
                    "star",
                    "step-backward",
                    "step-forward",
                    "stethoscope",
                    "sticky-note",
                    "stop",
                    "stop-circle",
                    "street-view",
                    "strikethrough",
                    "subscript",
                    "subway",
                    "suitcase",
                    "sun",
                    "superscript",
                    "subway1",
                    "table",
                    "tablet",
                    "tachometer",
                    "tag",
                    "tags",
                    "tasks",
                    "taxi",
                    "television",
                    "terminal",
                    "text-height",
                    "text-width",
                    "th",
                    "th-large",
                    "th-list",
                    "thermometer-0",
                    "thermometer-1",
                    "thermometer-2",
                    "thermometer-3",
                    "thermometer-4",
                    "thumb-tack",
                    "thumbs-down",
                    "thumbs-up",
                    "ticket",
                    "times",
                    "times-circle",
                    "times-rectangle",
                    "tint",
                    "toggle-off",
                    "toggle-on",
                    "toggle-down",
                    "toggle-left",
                    "toggle-right",
                    "toggle-up",
                    "trademark",
                    "train",
                    "transgender",
                    "transgender-alt",
                    "trash",
                    "trash-1",
                    "tree",
                    "trophy",
                    "truck",
                    "try",
                    "tty",
                    "turkish-lira",
                    "tv",
                    "umbrella",
                    "underline",
                    "universal-access",
                    "university",
                    "unlink",
                    "unlock",
                    "unlock-alt",
                    "unsorted",
                    "upload",
                    "usb",
                    "usd",
                    "user",
                    "user-circle",
                    "user-md",
                    "user-plus",
                    "user-secret",
                    "user-times",
                    "users",
                    "vcard",
                    "venus",
                    "venus-double",
                    "venus-mars",
                    "video-camera",
                    "volume-control-phone",
                    "volume-down",
                    "volume-off",
                    "volume-up",
                    "warning",
                    "wheelchair",
                    "wheelchair-alt",
                    "wifi",
                    "wikipedia-w",
                    "window-close",
                    "window-maximize",
                    "window-minimize",
                    "window-restore",
                    "windows",
                    "won",
                    "wrench",
                    "yen"
                ]
            }
        },
    }
</script>
